### ISSUE TITLE
Broken again in Firefox 121

### ISSUE THREAD

**Issue by bdusen** [zvuc/firefox-macos-native-tabbar#7] opened 2023-12-22 00:17 UTC
Seems to be broken again in Firefox 121. Can anyone confirm?

**Comment by roggmatsz** [comment] 2023-12-26 03:09
Can confirm, broken on 121 for both Sonoma and Monterey. I hope these issues don't seem like a nuisance; this is by far the best theme I have ever used on FF since the v4 days on Windows 7. Just trying to help it stay alive!

**Comment by zvuc** [comment] 2023-12-26 16:47
Try applying the latest update I just pushed (10a51e1672a33b23a693624618140a12f675cadf), for now it seems to bring back the translucency.

**Comment by roggmatsz** [comment] 2023-12-26 16:53
Its works again! Just confirmed.

**Comment by zvuc** [comment] 2023-12-26 17:01
Thanks for confirming! Closing issue now :)

**Closed as completed by zvuc** 2023-12-26 17:01 UTC

**Comment by bdusen** [comment] 2023-12-26 22:09
Thank you! It worked for me too!
